### ISSUE TITLE
Keeping connection is not enough

### ISSUE THREAD

**Issue by mallowlabs** [shokai/ruby-socket.io-client-simple#11]
Supporting Socket.IO 1.x is awesome, but I have a problem.

v1.1.3 can not keep WebSocket connection on my environment (Heroku+SSL).
I found that  `@websocket.send "2"  ## ping` sometimes raises exception and the ping thread dies.
I guess that exception handling is needed in the ping thread.
And I also found that `reconnect` is needed after raising exception in SSL environment.

I made a patch.
See https://github.com/mallowlabs/ruby-socket.io-client-simple/commit/9938f79454c6adf76715424392de8c240dfd0592
I feel this code is not smart, but it works for me.

I wish you help me.

**Comment by shokai** [comment]
thank you, I'll check.

**Comment by mallowlabs** [comment]
This issue is too old.
